insert into `Upgrade`
 (`name`, `description`, `default_number`, `resource_set_id`, `building_set_id`)
VALUES
('	Upgrade Granary	','	Upgrade Granary	',	0	,	1	,	1	),
('	Upgrade Granary and chikens house	','	Upgrade Granary and chikens house	',	0	,	2	,	2	),
('	Initialize the chikens	','	Initialize the chikens	',	0	,	3	,	3	),
('	F@ck this, i am out	','	F@ck this, i am out	',	0	,	4	,	4	),
('	Glue a chickens	','	Glue a chickens	',	0	,	5	,	5	),
('	Ruffle up a chikens	','	Ruffle up a chikens	',	0	,	6	,	6	),
('	Mother-in-law? I am in the army	','	Mother-in-law? I am in the army	',	0	,	7	,	7	),
('	Minecraft?	','	Minecraft?	',	0	,	8	,	8	),
('	USSC	','	USSC	',	0	,	9	,	9	),
('	Sling? Nooooo	','	Sling? Nooooo	',	0	,	10	,	10	),
('	Steelworkers	','	Steelworkers	',	0	,	11	,	11	),
('	Chickens infantry	','	Chickens infantry	',	0	,	12	,	12	),
('	Clumsy fame	','	Clumsy fame	',	0	,	13	,	13	),
('	New saws	','	New saws	',	0	,	14	,	14	),
('	Add optical sight to all bow	','	Add optical sight to all bow	',	0	,	15	,	15	),
('	Training of lancers	','	Training of lancers	',	0	,	16	,	16	),
('	Crazy professor	','	Crazy professor	',	0	,	17	,	17	),
('	Add fire transfer pen	','	Add fire transfer pen	',	0	,	18	,	18	),
('	ChiRambo	','	ChiRambo	',	0	,	19	,	19	),
('	Meditation	','	Meditation	',	0	,	20	,	20	),
('	Kill the Witcher	','	Kill the Witcher	',	0	,	21	,	21	),
('	Life for Ner Zul	','	Life for Ner Zul	',	0	,	22	,	22	),
('	Pesticides	','	Pesticides	',	0	,	23	,	23	),
('	Broiler	','	Broiler	',	0	,	24	,	24	),
('	Red bull	','	Red bull	',	0	,	25	,	25	),
('	Muscle gym	','	Muscle gym	',	0	,	26	,	26	),
('	New armor	','	New armor	',	0	,	27	,	27	),
('	Steel feathers	','	Steel feathers	',	0	,	28	,	28	),
('	Armed and dangerous	','	Armed and dangerous	',	0	,	29	,	29	),
('	Disney Princess? Really?	','	Disney Princess? Really?	',	0	,	30	,	30	);